/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 brush.gltf --transform
Author: plaggy (https://sketchfab.com/plaggy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cc0-paint-brush-3-5e38a7f8f1dd44cf859b23258c471445
Title: CC0 - Paint Brush 3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brush-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PaintBrush3_PaintBrush3_0.geometry} material={materials.PaintBrush3} rotation={[-1.771, -0.506, -0.098]} scale={0.1} />
      <mesh geometry={nodes.PaintBrush3v2_PaintBrush3v2_0.geometry} material={materials.PaintBrush3v2} position={[0, 0, -0.013]} rotation={[-1.751, -0.25, -0.045]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/brush-transformed.glb')
