/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 gamepad.gltf --transform
Author: Nidal Ghonaim (https://sketchfab.com/Nyawning)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-gamepad-5c6f14140c8f492391c464c308190c62
Title: Nintendo Gamepad
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gamepad-transformed.glb')


  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2.2, 0, 0]} scale={0.8}>
        <mesh geometry={nodes.GamePad1_polySurface13_White_0.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('/gamepad-transformed.glb')
